### ISSUE TITLE
请问如何调用 content 指定的实例内部的方法

### ISSUE THREAD

**Issue by Aurorxa** [caroundsky/el-plus-dialog-service#3]
![1](https://user-images.githubusercontent.com/25677587/190182409-6a41d3cd-c276-4717-93d4-9468ac66c4a8.PNG)

**Comment by caroundsky** [comment]
AdminAdd 组件内部需要使用defineExpose暴露出指定方法

**Comment by Aurorxa** [comment]
> AdminAdd 组件内部需要使用defineExpose暴露出指定方法

谢谢，已经可以了，element-plus 报警报，能否有时间帮忙弄下，重发一版
